### ISSUE TITLE
临时解决：wepy调用时找不到loadedWxParserImg，tapWxParserImg函数

### ISSUE THREAD

**Issue by xusion** [ifanrx/wxParser#3]
VM36367:1 Do not have loadedWxParserImg handler in current page
VM36367:1 Do not have tapWxParserImg handler in current page

解决方法：
 methods = {
    loadedWxParserImg(e){
      console.log('loadedWxParserImg',e);
      this.loadedWxParserImg(e);
    },
    tapWxParserImg(e){
      console.log('tapWxParserImg',e);
      this.tapWxParserImg(e);
    }
  };
在wepy页面里methods添加上上面的函数。

**Comment by heshiyou** [comment]
有劳直接提 PR 我们看下。

**Comment by xusion** [comment]
刚刚提交了一份PR，可以看看
