### ISSUE TITLE
在开发者工具里引用插件正常，预览的时候报“找不到组件”错误

### ISSUE THREAD

**Issue by xxrt** [ifanrx/wxParser#6]
你好，用了这个插件以后，在开发者工具里使用正常，但是在手机上预览的时候报错，基础库版本2.0.0和1.9.2都是这个现象，请问如何解决？

![image](https://user-images.githubusercontent.com/36843313/39029513-c2620ee2-448e-11e8-9688-22c6c23ee5d8.png)

**Comment by YaoKaiLun** [comment]
![image](https://user-images.githubusercontent.com/11460856/39707179-3934d0c6-5246-11e8-9e3f-805c3a723dd1.png)
更新开发者工具即可

**Comment by YaoKaiLun** [comment]
更新开发者工具即可
<img width="712" alt="_ _" src="https://user-images.githubusercontent.com/11460856/39707249-74425a1c-5246-11e8-85b7-8aff149b8fd0.png">
